In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("/content/covid_toy.csv")
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [3]:
df.shape

(100, 6)

In [5]:
from sklearn.model_selection import train_test_split

In [13]:
X = df.drop(columns=["has_covid"]) #drop y data
y = df["has_covid"]

In [15]:
X.head()

   age  gender  fever cough     city
0   60    Male  103.0  Mild  Kolkata
1   27    Male  100.0  Mild    Delhi
2   42    Male  101.0  Mild    Delhi
3   31  Female   98.0  Mild  Kolkata
4   65  Female  101.0  Mild   Mumbai

In [16]:
Y.head()

0     No
1    Yes
2     No
3     No
4     No
Name: has_covid, dtype: object

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [19]:
X_train

    age  gender  fever   cough       city
55   81  Female  101.0    Mild     Mumbai
88    5  Female  100.0    Mild    Kolkata
26   19  Female  100.0    Mild    Kolkata
42   27    Male  100.0    Mild      Delhi
69   73  Female  103.0    Mild      Delhi
..  ...     ...    ...     ...        ...
60   24  Female  102.0  Strong  Bangalore
71   75  Female  104.0  Strong      Delhi
14   51    Male  104.0    Mild  Bangalore
92   82  Female  102.0  Strong    Kolkata
51   11  Female  100.0  Strong    Kolkata

[80 rows x 5 columns]

In [20]:
y_train

55    Yes
88     No
26    Yes
42    Yes
69     No
     ...
60    Yes
71     No
14     No
92     No
51    Yes
Name: has_covid, Length: 80, dtype: object

In [21]:
X_test

    age  gender  fever   cough       city
83   17  Female  104.0    Mild    Kolkata
53   83    Male   98.0    Mild      Delhi
70   68  Female  101.0  Strong      Delhi
45   72    Male   99.0    Mild  Bangalore
44   20    Male  102.0  Strong      Delhi
39   50  Female  103.0    Mild    Kolkata
22   71  Female   98.0  Strong    Kolkata
80   14  Female   99.0    Mild     Mumbai
10   75  Female    NaN    Mild      Delhi
0    60    Male  103.0    Mild    Kolkata
18   64  Female   98.0    Mild  Bangalore
30   15    Male  101.0    Mild      Delhi
73   34    Male   98.0  Strong    Kolkata
33   26  Female   98.0    Mild    Kolkata
90   59  Female   99.0  Strong      Delhi
4    65  Female  101.0    Mild     Mumbai
76   80    Male  100.0    Mild  Bangalore
77    8  Female  101.0    Mild    Kolkata
12   25  Female   99.0  Strong    Kolkata
31   83    Male  103.0    Mild    Kolkata

In [22]:
y_test

83     No
53    Yes
70     No
45     No
44     No
39     No
22    Yes
80    Yes
10     No
0      No
18    Yes
30    Yes
73    Yes
33     No
90     No
4      No
76    Yes
77     No
12     No
31     No
Name: has_covid, dtype: object