In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.impute import SimpleImputer #for missing value handling
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.read_csv("/content/covid_toy.csv")

In [4]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [5]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2,
                                                random_state=42)

In [7]:
X_train

    age  gender  fever   cough       city
55   81  Female  101.0    Mild     Mumbai
88    5  Female  100.0    Mild    Kolkata
26   19  Female  100.0    Mild    Kolkata
42   27    Male  100.0    Mild      Delhi
69   73  Female  103.0    Mild      Delhi
..  ...     ...    ...     ...        ...
60   24  Female  102.0  Strong  Bangalore
71   75  Female  104.0  Strong      Delhi
14   51    Male  104.0    Mild  Bangalore
92   82  Female  102.0  Strong    Kolkata
51   11  Female  100.0  Strong    Kolkata

[80 rows x 5 columns]

In [8]:
# adding simple imputer to fever column for missing value handling
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])

X_train_fever.shape

(80, 1)

In [9]:
X_train_fever

array([[101.],
       [100.],
       [100.],
       [100.],
       [103.],
       [103.],
       [102.],
       [101.],
       [101.],
       [101.],
       [ 98.],
       [104.],
       [103.],
       [104.],
       [100.],
       [101.],
       [104.],
       [102.],
       [102.],
       [103.],
       [104.],
       [102.],
       [101.],
       [104.],
       [102.],
       [101.],
       [ 99.],
       [101.],
       [104.],
       [102.],
       [100.],
       [ 98.],
       [ 98.],
       [101.],
       [100.],
       [100.],
       [101.],
       [104.],
       [101.],
       [103.],
       [101.],
       [ 98.],
       [ 99.],
       [ 99.],
       [101.],
       [ 99.],
       [101.],
       [104.],
       [ 98.],
       [101.],
       [103.],
       [101.],
       [ 98.],
       [ 99.],
       [ 98.],
       [ 99.],
       [102.],
       [101.],
       [101.],
       [104.],
       [100.],
       [ 98.],
       [100.],
       [101.],
       [100.],
       [100.],
       [ 98.],
       [101.],
       [ 98.],
       [101.],
       [101.],
       [104.],
       [104.],
       [ 98.],
       [ 98.],
       [102.],
       [104.],
       [104.],
       [102.],
       [100.]])

In [10]:
# Ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])

X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [11]:
X_train_cough

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.]])

In [12]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop='first',sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape

(80, 4)

In [13]:
X_train_gender_city

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 1.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 1.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.]])

In [14]:
X_train.head()

    age  gender  fever cough     city
55   81  Female  101.0  Mild   Mumbai
88    5  Female  100.0  Mild  Kolkata
26   19  Female  100.0  Mild  Kolkata
42   27    Male  100.0  Mild    Delhi
69   73  Female  103.0  Mild    Delhi

In [17]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

X_train_age

array([[81],
       [ 5],
       [19],
       [27],
       [73],
       [70],
       [49],
       [51],
       [64],
       [83],
       [65],
       [18],
       [16],
       [16],
       [27],
       [84],
       [51],
       [69],
       [82],
       [69],
       [44],
       [74],
       [20],
       [12],
       [33],
       [42],
       [65],
       [23],
       [56],
       [64],
       [13],
       [31],
       [40],
       [49],
       [19],
       [11],
       [14],
       [42],
       [38],
       [46],
       [71],
       [10],
       [60],
       [22],
       [19],
       [65],
       [19],
       [54],
       [81],
       [20],
       [48],
       [82],
       [23],
       [66],
       [ 5],
       [49],
       [ 5],
       [34],
       [79],
       [ 6],
       [10],
       [69],
       [55],
       [34],
       [27],
       [47],
       [73],
       [42],
       [80],
       [47],
       [38],
       [34],
       [25],
       [24],
       [12],
       [24],
       [75],
       [51],
       [82],
       [11]])

In [18]:
# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

# Concatenation

In [19]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed.shape

(80, 7)

In [20]:
X_train_transformed

array([[ 81., 101.,   0.,   0.,   0.,   1.,   0.],
       [  5., 100.,   0.,   0.,   1.,   0.,   0.],
       [ 19., 100.,   0.,   0.,   1.,   0.,   0.],
       [ 27., 100.,   1.,   1.,   0.,   0.,   0.],
       [ 73., 103.,   0.,   1.,   0.,   0.,   0.],
       [ 70., 103.,   1.,   0.,   1.,   0.,   1.],
       [ 49., 102.,   0.,   1.,   0.,   0.,   0.],
       [ 51., 101.,   0.,   0.,   1.,   0.,   1.],
       [ 64., 101.,   0.,   1.,   0.,   0.,   0.],
       [ 83., 101.,   0.,   0.,   1.,   0.,   0.],
       [ 65.,  98.,   0.,   0.,   0.,   1.,   0.],
       [ 18., 104.,   0.,   0.,   0.,   0.,   0.],
       [ 16., 103.,   0.,   0.,   0.,   0.,   0.],
       [ 16., 104.,   1.,   0.,   1.,   0.,   0.],
       [ 27., 100.,   1.,   0.,   1.,   0.,   0.],
       [ 84., 101.,   0.,   0.,   0.,   0.,   0.],
       [ 51., 104.,   1.,   0.,   1.,   0.,   0.],
       [ 69., 102.,   0.,   0.,   0.,   0.,   0.],
       [ 82., 102.,   0.,   0.,   0.,   0.,   1.],
       [ 69., 103.,   0.,   0.,   1.,   0.,   0.],
       [ 44., 104.,   1.,   0.,   0.,   1.,   0.],
       [ 74., 102.,   1.,   0.,   0.,   1.,   0.],
       [ 20., 101.,   0.,   0.,   0.,   1.,   1.],
       [ 12., 104.,   0.,   0.,   0.,   0.,   0.],
       [ 33., 102.,   0.,   1.,   0.,   0.,   1.],
       [ 42., 101.,   0.,   0.,   0.,   0.,   1.],
       [ 65.,  99.,   1.,   1.,   0.,   0.,   0.],
       [ 23., 101.,   1.,   0.,   0.,   1.,   0.],
       [ 56., 104.,   0.,   0.,   0.,   0.,   1.],
       [ 64., 102.,   1.,   0.,   0.,   0.,   0.],
       [ 13., 100.,   0.,   0.,   1.,   0.,   1.],
       [ 31.,  98.,   0.,   0.,   1.,   0.,   0.],
       [ 40.,  98.,   0.,   1.,   0.,   0.,   1.],
       [ 49., 101.,   0.,   1.,   0.,   0.,   0.],
       [ 19., 100.,   0.,   0.,   0.,   0.,   1.],
       [ 11., 100.,   1.,   0.,   0.,   0.,   0.],
       [ 14., 101.,   1.,   0.,   0.,   0.,   1.],
       [ 42., 104.,   1.,   0.,   0.,   1.,   0.],
       [ 38., 101.,   0.,   0.,   0.,   0.,   0.],
       [ 46., 103.,   1.,   0.,   0.,   0.,   1.],
       [ 71., 101.,   1.,   0.,   1.,   0.,   1.],
       [ 10.,  98.,   0.,   0.,   1.,   0.,   1.],
       [ 60.,  99.,   0.,   0.,   0.,   1.,   0.],
       [ 22.,  99.,   0.,   0.,   0.,   0.,   0.],
       [ 19., 101.,   1.,   1.,   0.,   0.,   0.],
       [ 65.,  99.,   1.,   0.,   0.,   0.,   0.],
       [ 19., 101.,   0.,   0.,   0.,   1.,   0.],
       [ 54., 104.,   0.,   0.,   1.,   0.,   1.],
       [ 81.,  98.,   0.,   0.,   0.,   1.,   1.],
       [ 20., 101.,   0.,   0.,   0.,   0.,   0.],
       [ 48., 103.,   0.,   0.,   1.,   0.,   0.],
       [ 82., 101.,   1.,   0.,   1.,   0.,   0.],
       [ 23.,  98.,   1.,   0.,   0.,   1.,   1.],
       [ 66.,  99.,   1.,   0.,   0.,   0.,   1.],
       [  5.,  98.,   0.,   0.,   0.,   1.,   1.],
       [ 49.,  99.,   0.,   0.,   0.,   0.,   1.],
       [  5., 102.,   1.,   0.,   1.,   0.,   0.],
       [ 34., 101.,   0.,   1.,   0.,   0.,   1.],
       [ 79., 101.,   1.,   0.,   1.,   0.,   1.],
       [  6., 104.,   0.,   0.,   1.,   0.,   0.],
       [ 10., 100.,   1.,   0.,   0.,   0.,   0.],
       [ 69.,  98.,   0.,   0.,   0.,   1.,   1.],
       [ 55., 100.,   1.,   0.,   1.,   0.,   0.],
       [ 34., 101.,   0.,   0.,   0.,   1.,   1.],
       [ 27., 100.,   1.,   1.,   0.,   0.,   0.],
       [ 47., 100.,   0.,   0.,   0.,   0.,   1.],
       [ 73.,  98.,   1.,   0.,   0.,   0.,   0.],
       [ 42., 101.,   1.,   1.,   0.,   0.,   0.],
       [ 80.,  98.,   0.,   1.,   0.,   0.,   0.],
       [ 47., 101.,   1.,   0.,   0.,   0.,   1.],
       [ 38., 101.,   1.,   1.,   0.,   0.,   0.],
       [ 34., 104.,   0.,   1.,   0.,   0.,   1.],
       [ 25., 104.,   1.,   0.,   0.,   0.,   0.],
       [ 24.,  98.,   1.,   0.,   1.,   0.,   0.],
       [ 12.,  98.,   1.,   0.,   0.,   0.,   1.],
       [ 24., 102.,   0.,   0.,   0.,   0.,   1.],
       [ 75., 104.,   0.,   1.,   0.,   0.,   1.],
       [ 51., 104.,   1.,   0.,   0.,   0.,   0.],
       [ 82., 102.,   0.,   0.,   1.,   0.,   1.],
       [ 11., 100.,   0.,   0.,   1.,   0.,   1.]])

# Column Transformation Automatic way

In [22]:
from sklearn.compose import ColumnTransformer

In [23]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [24]:
new_data = transformer.fit_transform(X_train)

new_data

array([[101.,   0.,   0.,   0.,   0.,   1.,  81.],
       [100.,   0.,   0.,   0.,   1.,   0.,   5.],
       [100.,   0.,   0.,   0.,   1.,   0.,  19.],
       [100.,   0.,   1.,   1.,   0.,   0.,  27.],
       [103.,   0.,   0.,   1.,   0.,   0.,  73.],
       [103.,   1.,   1.,   0.,   1.,   0.,  70.],
       [102.,   0.,   0.,   1.,   0.,   0.,  49.],
       [101.,   1.,   0.,   0.,   1.,   0.,  51.],
       [101.,   0.,   0.,   1.,   0.,   0.,  64.],
       [101.,   0.,   0.,   0.,   1.,   0.,  83.],
       [ 98.,   0.,   0.,   0.,   0.,   1.,  65.],
       [104.,   0.,   0.,   0.,   0.,   0.,  18.],
       [103.,   0.,   0.,   0.,   0.,   0.,  16.],
       [104.,   0.,   1.,   0.,   1.,   0.,  16.],
       [100.,   0.,   1.,   0.,   1.,   0.,  27.],
       [101.,   0.,   0.,   0.,   0.,   0.,  84.],
       [104.,   0.,   1.,   0.,   1.,   0.,  51.],
       [102.,   0.,   0.,   0.,   0.,   0.,  69.],
       [102.,   1.,   0.,   0.,   0.,   0.,  82.],
       [103.,   0.,   0.,   0.,   1.,   0.,  69.],
       [104.,   0.,   1.,   0.,   0.,   1.,  44.],
       [102.,   0.,   1.,   0.,   0.,   1.,  74.],
       [101.,   1.,   0.,   0.,   0.,   1.,  20.],
       [104.,   0.,   0.,   0.,   0.,   0.,  12.],
       [102.,   1.,   0.,   1.,   0.,   0.,  33.],
       [101.,   1.,   0.,   0.,   0.,   0.,  42.],
       [ 99.,   0.,   1.,   1.,   0.,   0.,  65.],
       [101.,   0.,   1.,   0.,   0.,   1.,  23.],
       [104.,   1.,   0.,   0.,   0.,   0.,  56.],
       [102.,   0.,   1.,   0.,   0.,   0.,  64.],
       [100.,   1.,   0.,   0.,   1.,   0.,  13.],
       [ 98.,   0.,   0.,   0.,   1.,   0.,  31.],
       [ 98.,   1.,   0.,   1.,   0.,   0.,  40.],
       [101.,   0.,   0.,   1.,   0.,   0.,  49.],
       [100.,   1.,   0.,   0.,   0.,   0.,  19.],
       [100.,   0.,   1.,   0.,   0.,   0.,  11.],
       [101.,   1.,   1.,   0.,   0.,   0.,  14.],
       [104.,   0.,   1.,   0.,   0.,   1.,  42.],
       [101.,   0.,   0.,   0.,   0.,   0.,  38.],
       [103.,   1.,   1.,   0.,   0.,   0.,  46.],
       [101.,   1.,   1.,   0.,   1.,   0.,  71.],
       [ 98.,   1.,   0.,   0.,   1.,   0.,  10.],
       [ 99.,   0.,   0.,   0.,   0.,   1.,  60.],
       [ 99.,   0.,   0.,   0.,   0.,   0.,  22.],
       [101.,   0.,   1.,   1.,   0.,   0.,  19.],
       [ 99.,   0.,   1.,   0.,   0.,   0.,  65.],
       [101.,   0.,   0.,   0.,   0.,   1.,  19.],
       [104.,   1.,   0.,   0.,   1.,   0.,  54.],
       [ 98.,   1.,   0.,   0.,   0.,   1.,  81.],
       [101.,   0.,   0.,   0.,   0.,   0.,  20.],
       [103.,   0.,   0.,   0.,   1.,   0.,  48.],
       [101.,   0.,   1.,   0.,   1.,   0.,  82.],
       [ 98.,   1.,   1.,   0.,   0.,   1.,  23.],
       [ 99.,   1.,   1.,   0.,   0.,   0.,  66.],
       [ 98.,   1.,   0.,   0.,   0.,   1.,   5.],
       [ 99.,   1.,   0.,   0.,   0.,   0.,  49.],
       [102.,   0.,   1.,   0.,   1.,   0.,   5.],
       [101.,   1.,   0.,   1.,   0.,   0.,  34.],
       [101.,   1.,   1.,   0.,   1.,   0.,  79.],
       [104.,   0.,   0.,   0.,   1.,   0.,   6.],
       [100.,   0.,   1.,   0.,   0.,   0.,  10.],
       [ 98.,   1.,   0.,   0.,   0.,   1.,  69.],
       [100.,   0.,   1.,   0.,   1.,   0.,  55.],
       [101.,   1.,   0.,   0.,   0.,   1.,  34.],
       [100.,   0.,   1.,   1.,   0.,   0.,  27.],
       [100.,   1.,   0.,   0.,   0.,   0.,  47.],
       [ 98.,   0.,   1.,   0.,   0.,   0.,  73.],
       [101.,   0.,   1.,   1.,   0.,   0.,  42.],
       [ 98.,   0.,   0.,   1.,   0.,   0.,  80.],
       [101.,   1.,   1.,   0.,   0.,   0.,  47.],
       [101.,   0.,   1.,   1.,   0.,   0.,  38.],
       [104.,   1.,   0.,   1.,   0.,   0.,  34.],
       [104.,   0.,   1.,   0.,   0.,   0.,  25.],
       [ 98.,   0.,   1.,   0.,   1.,   0.,  24.],
       [ 98.,   1.,   1.,   0.,   0.,   0.,  12.],
       [102.,   1.,   0.,   0.,   0.,   0.,  24.],
       [104.,   1.,   0.,   1.,   0.,   0.,  75.],
       [104.,   0.,   1.,   0.,   0.,   0.,  51.],
       [102.,   1.,   0.,   0.,   1.,   0.,  82.],
       [100.,   1.,   0.,   0.,   1.,   0.,  11.]])

In [25]:
transformer.transform(X_test).shape

(20, 7)